import {
    Award,
    Shield,
    Flame,
    Leaf,
    DollarSign,
    Cloud,
    Anchor,
    Crown,
    Sprout,
} from 'lucide-react';

export const TOP_PICKS_CATEGORIES = [
    {
        slug: 'best-overall-mattress',
        category: 'Best Overall Mattress',
        title: 'WinkBed Original',
        imageParams: 'from-[#1a1a1a] to-[#242f40]',
        icon: <Award className="text-golden-bronze" size={32} />,
        tag: "Editor's Choice",
        highlight: 'Perfect balance of luxury hybrid comfort and back support.',
        keyStat: '98% Durability Score',
        reviewHref: '/mattress-reviews/winkbed-original',
        pros: ['Lifetime Warranty', 'Exceptional Back Support', 'Cooling Tencel Cover'],
        alsoConsider: [
            { title: 'DreamCloud Premier Rest', href: '/mattress-reviews/dreamcloud-premier-rest' },
            { title: 'Leesa Legend', href: '/mattress-reviews/leesa-legend' },
            { title: 'Purple Original', href: '/mattress-reviews/purple-original' },
        ],
    },
    {
        slug: 'best-mattress-for-back-pain',
        category: 'Best Mattress for Back Pain',
        title: 'WinkBed Original',
        imageParams: 'from-[#1a1a1a] to-[#242f40]',
        icon: <Anchor className="text-golden-bronze" size={32} />,
        tag: 'Spine Aligned',
        highlight: 'Zoned coil system actively pushes back to align the spine.',
        keyStat: 'Zoned Lumbar Support',
        reviewHref: '/mattress-reviews/winkbed-original',
        pros: ['Pressure-Relieving Pillow Top', '3 Firmness Options', 'Chiropractor Recommended'],
        alsoConsider: [
            { title: 'Helix Plus', href: '/mattress-reviews/helix-plus' },
            { title: 'Leesa Legend', href: '/mattress-reviews/leesa-legend' },
            { title: 'Purple Original', href: '/mattress-reviews/purple-original' },
        ],
    },
    {
        slug: 'best-cooling-mattress',
        category: 'Best Cooling Mattress',
        title: 'Purple Original',
        imageParams: 'from-[#4B1E78] to-[#662D91]',
        icon: <Flame className="text-golden-bronze" size={32} />,
        tag: 'Most Breathable',
        highlight: "The grid structure allows massive airflow that foams can't match.",
        keyStat: 'Open-Grid Airflow',
        reviewHref: '/mattress-reviews/purple-original',
        pros: ['GelFlex Grid Technology', 'Instant Response', 'Sleeps Neutral'],
        alsoConsider: [
            { title: 'Brooklyn Bedding Aurora Luxe', href: '/mattress-reviews/brooklyn-bedding-aurora-luxe' },
            { title: 'WinkBed Original', href: '/mattress-reviews/winkbed-original' },
            { title: 'DreamCloud Premier Rest', href: '/mattress-reviews/dreamcloud-premier-rest' },
        ],
    },
    {
        slug: 'best-organic-mattress',
        category: 'Best Organic Mattress',
        title: 'WinkBed EcoCloud',
        imageParams: 'from-[#3f6212] to-[#65a30d]',
        icon: <Leaf className="text-golden-bronze" size={32} />,
        tag: 'Eco-Friendly',
        highlight: 'Natural latex comfort with a durable hybrid support core.',
        keyStat: 'Latex + Coil Hybrid',
        reviewHref: '/mattress-reviews/winkbed-ecocloud',
        pros: ['Hypoallergenic', 'Sustainable Materials', 'Responsive (No “Stuck” Feel)'],
        alsoConsider: [
            { title: 'Best Latex Mattress', href: '/top-picks/best-latex-mattress' },
            { title: 'WinkBed Original', href: '/mattress-reviews/winkbed-original' },
            { title: 'Purple Original', href: '/mattress-reviews/purple-original' },
        ],
    },
    {
        slug: 'best-latex-mattress',
        category: 'Best Latex Mattress',
        title: 'WinkBed EcoCloud',
        imageParams: 'from-[#3f6212] to-[#65a30d]',
        icon: <Sprout className="text-golden-bronze" size={32} />,
        tag: 'Latex Pick',
        highlight: 'Latex offers springy support and long-term resilience when foams soften.',
        keyStat: 'Natural Latex Comfort',
        reviewHref: '/mattress-reviews/winkbed-ecocloud',
        pros: ['More Durable Than Typical Foams', 'Responsive Feel', 'Breathable Comfort Layers'],
        alsoConsider: [
            { title: 'Best Organic Mattress', href: '/top-picks/best-organic-mattress' },
            { title: 'WinkBed Original', href: '/mattress-reviews/winkbed-original' },
            { title: 'Helix Plus', href: '/mattress-reviews/helix-plus' },
        ],
    },
    {
        slug: 'best-value-mattress',
        category: 'Best Value Mattress',
        title: 'Nectar Classic',
        imageParams: 'from-[#1d4ed8] to-[#3b82f6]',
        icon: <DollarSign className="text-golden-bronze" size={32} />,
        tag: 'Best Budget',
        highlight: 'The lowest price that still clears our durability baseline.',
        keyStat: '365-Night Trial',
        reviewHref: '/mattress-reviews/nectar-classic',
        pros: ['Forever Warranty', 'Zero Motion Transfer', 'Deep Contouring'],
        alsoConsider: [
            { title: 'Nectar Premier', href: '/mattress-reviews/nectar-premier' },
            { title: 'Leesa Original', href: '/mattress-reviews/leesa-original' },
            { title: 'DreamCloud Premier Rest', href: '/mattress-reviews/dreamcloud-premier-rest' },
        ],
    },
    {
        slug: 'best-mattress-for-side-sleepers',
        category: 'Best Mattress for Side Sleepers',
        title: 'Leesa Legend',
        imageParams: 'from-[#1e293b] to-[#475569]',
        icon: <Cloud className="text-golden-bronze" size={32} />,
        tag: 'Pressure Relief',
        highlight: 'Targeted shoulder/hip relief without the “stuck” memory-foam drag.',
        keyStat: 'Zoned Support',
        reviewHref: '/mattress-reviews/leesa-legend',
        pros: ['Organic Cotton Cover', 'Hybrid Comfort', 'Medium-Plush Feel'],
        alsoConsider: [
            { title: 'Leesa Original', href: '/mattress-reviews/leesa-original' },
            { title: 'WinkBed Original', href: '/mattress-reviews/winkbed-original' },
            { title: 'Nectar Premier', href: '/mattress-reviews/nectar-premier' },
        ],
    },
    {
        slug: 'best-mattress-for-heavy-sleepers',
        category: 'Best Mattress for Heavy Sleepers',
        title: 'Helix Plus',
        imageParams: 'from-[#000000] to-[#333333]',
        icon: <Shield className="text-golden-bronze" size={32} />,
        tag: 'Plus Size',
        highlight: 'Built with higher-density materials to resist early sagging.',
        keyStat: 'Heavy-Duty Build',
        reviewHref: '/mattress-reviews/helix-plus',
        pros: ['Reinforced Construction', 'Sag-Resistant Foams', 'Firm Support'],
        alsoConsider: [
            { title: 'WinkBed Original', href: '/mattress-reviews/winkbed-original' },
            { title: 'DreamCloud Premier Rest', href: '/mattress-reviews/dreamcloud-premier-rest' },
            { title: 'Purple Original', href: '/mattress-reviews/purple-original' },
        ],
    },
    {
        slug: 'best-luxury-mattress',
        category: 'Best Luxury Mattress',
        title: 'DreamCloud Premier Rest',
        imageParams: 'from-[#0f172a] to-[#334155]',
        icon: <Crown className="text-golden-bronze" size={32} />,
        tag: 'Hotel Luxury',
        highlight: 'Thick comfort layers paired with a durable hybrid core.',
        keyStat: '16-Inch Profile',
        reviewHref: '/mattress-reviews/dreamcloud-premier-rest',
        pros: ['Cashmere Blend Cover', 'Multi-Layer Design', 'Plush “Hotel” Feel'],
        alsoConsider: [
            { title: 'WinkBed Original', href: '/mattress-reviews/winkbed-original' },
            { title: 'Leesa Legend', href: '/mattress-reviews/leesa-legend' },
            { title: 'Purple Original', href: '/mattress-reviews/purple-original' },
        ],
    },
];

export const TOP_PICKS_BY_SLUG = Object.fromEntries(
    TOP_PICKS_CATEGORIES.map((category) => [category.slug, category])
);
